### ISSUE TITLE
Dealing with GodSVG's blurriness

### ISSUE THREAD

**Issue by MewPurPur** [MewPurPur/GodSVG#342]
The current situation with GodSVG's scaling is very unhappy.

### Disabled scaling:

- It just makes the UI too small in my opinion. It's better for something to be too big, than to be forced too small.

### Canvas items scaling mode (current):

- It scales most things regularly, so they become blurry.

-----

The current idea is to move to disabled scaling mode, but I've decided that its downside is worse than that of canvas item scaling. So not until a setting for editor scale is added.

I imagine such a setting could go from something like `1x` to `2x`. I am not sure how it would be implemented: I imagine with lots of bubblegum and shoestrings. But the main things are:

- The theme needs to be updated whenever this setting changes. So for example for 2x, things like border width and corner radius need to be doubled (some extra detail might be needed for high corner radius too).
- A lot of things throughout the UI need to be updated too. Where do I even begin... Basically anything transform-related, for example minimum sizes, needs to be multiplied or tweaked in other ways manually, via script.
- The SVGs used for icons will likely need some logic around reimporting them to the correct size. (Note: Keep track of https://github.com/godotengine/godot/pull/86022)
- HandlerGUI could have a static variable "edscale" used for all the above.

I feel like some things may be doable, to some extent, in more sweeping ways than via script, but I don't know which ones, how, and if there would be any complications in using those ways.

**Comment by colleen05** [comment]
I have a 1440p monitor at a higher PPI than your typical 21"-27" 1080p display. This means that things typically look smaller on my monitor if they were made for 1080p displays. In my opinion, even with the probably-smaller-than-intended UI elements, the UI elements in the default window size are perfectly fine!

I would recommend disabling scaling by default and having UI scaling options in the preferences. This would allow for better rendering code to be written in the future for cleaner large-scale UI (e.g., a 24x24 button at 2x scale is actually rendered at 48x48, rather than the window texture being scaled up with texture filtering).

I propose three scaling options:
1. **No scaling:** Everything is rendered to a texture the size of the window. The user may decide to user their OS's native window scaling.
2. **Factor scale:** The user selects a factor (e.g, 150%), and the UI is rendered to a texture that is equal to the window's size when scaled by the selected factor. I.e., a 1280x720 window with 200% factored scaling will have UI rendered at 640x360.
3. **Fixed size:** The user chooses a vertical and horizontal resolution of the UI. They may choose to "lock" either the width, height, or both dimensions, such that the "unlocked" dimension is solved for the aspect resolution of the window. For example, if the user selects a *locked* height of 720px (with the width being *unlocked*), and their window has an aspect ratio of 2:1, the UI will be rendered to a texture of 1440x720.

Additionally, they should be able to choose whether UI is scaled per nearest-neighbour ("Pixel-perfect"?) and bilinear ("Smoothed"?).

In the future, the texture scaling could be removed completely, and (as suggested before,) be replaced with code that actually renders things with the appropriate scale at full resolution. However, as GodSVG is still in alpha, I doubt this is a major focus at the moment.

**Comment by MewPurPur** [comment]
Yeah, that's the exact plan. I plan to work on theme generation soon, so that'll unlock one of the points for implementing factor scale. But I can't have a small texture get upscaled, that'd just be blurry all over I think.

**Comment by Pacomatic1** [comment]
Maybe make those textures with SVGs and then re-render them according to the size at which they'll be seen?
Seems good at least to my meager knowledge.

**Comment by MewPurPur** [comment]
Last time I tried it didn't find a way to apply this throughout the whole application.

**Comment by MewPurPur** [comment]
Pretty much solved by #661
