### ISSUE TITLE
Consider the middle mouse button (Comment if you have ideas)

### ISSUE THREAD

**Issue by MewPurPur** [MewPurPur/GodSVG#472]
In general, all around the codebase, we only respond to left and right mouse button clicks, never middle.

My current line of thought is, it shouldn't be an important, and not a destructive action. This would make parity with various devices harder. I'm thinking it should provide alternative ways of doing certain things. But I never use the middle mouse button, so we should probably get to know what people would expect from it.

**Comment by Swarkin** [comment]
Middle mouse on linux is used for pasting iirc.
The only common use case I can think of is panning the view with MMB.

**Comment by MewPurPur** [comment]
Panning the view is with LMB already.

**Comment by Kiisu-Master** [comment]
Panning the view with MMB already works..

**Comment by Pacomatic1** [comment]
With the way that you're proposing this it really feels like a feature for the sake of adding something; not something people actively want or a possible improvement.

**Comment by MewPurPur** [comment]
Different users have different user cases, often things you don't even consider, but you have to accommodate all of them. If you're used to shortcuts, you may not even consider that other people are used to drag-and-drop, right-mouse-button, or all kinds of things I can't even think of right now.

While accommodating many end users' use cases can result in bloat, here this doesn't hold. There's categorically no way considering the Middle Mouse Button is bloat, because if you don't need it, it wouldn't get in your way.

Finally, this is a small app that gets external feedback very rarely. If I waited for external feedback before trying to move things forward myself, GodSVG wouldn't get anywhere.

**Comment by Kiisu-Master** [comment]
I don't see how adding good input management bloats software.
In GodSVG the input handling is definitely not the slow part.
Also, heres a list of middle mouse button actions that i think can be considered standard in software:
- auto-scroll
- close tab
- open sth in new tab
- pan (works in GodSVG)
- paste text (linux only)

 In Blender there is also some nice stuff:
- trigger automatic axis snapping when transforming stuff
- ctrl + middle mouse drag zooms in and out (works in GodSVG)

I am disappointed when software doesn't implement these, because I am used to using my middle mouse button too, like any other button.

**Comment by MewPurPur** [comment]
Autoscroll as in, scroll when holding MMB and moving your mouse up or down?

**Comment by MewPurPur** [comment]
We explored this, and only came up with one missing use case of scrolling with MMB+Drag. I don't think there's any way to implement it without significant downsides. So I'm closing this for now.
