### ISSUE TITLE
Initiating a drag event when nothing is selected causes a crash

### ISSUE THREAD

**Issue by MewPurPur** [MewPurPur/GodSVG#823]
1. Hold the cursor pressed over an element in the list
2. Press Esc while still holding, to deselect the element
3. Drag the cursor around
4. Crash

**Comment by MarouaneMebarki** [comment]
It happens because of the static function 'filter_descendant_xids' at 
res://src/utils/Utils.gd line: 113 

the 'new_xids' array is empty 
but at line: 113
you are assigning 'last_acepted' to a value don't exist:  **Out of bound exception**

i honestly didn't explore the project code further
but a temporary quick fix :

```
static func filter_descendant_xids(xids: Array[PackedInt32Array]) -> Array[PackedInt32Array]:
	if xids.is_empty():
		return xids
	var new_xids: Array[PackedInt32Array] = xids.duplicate()
	new_xids.sort_custom(Utils.compare_xids_r)
	# Linear scan to filter out the descendants.
	var last_accepted := new_xids[0]
	var i := 1
	while i < new_xids.size():
		var xid := new_xids[i]
		if Utils.is_xid_parent_or_self(last_accepted, xid):
			new_xids.remove_at(i)
		else:
			last_accepted = new_xids[i]
			i += 1
	return new_xids

```
